# Generated by Django 5.1.4 on 2025-01-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='Purchased_At',
        ),
    ]
